name: Build Tetris C++ Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev g++

    - name: Build the project
      run: |
        make clean
        make

    - name: Run binary (headless test)
      run: |
        echo "Skipping actual execution since SDL2 requires display"
    - name: Notify Discord after a run
      if: always()
      run: |
        status="${{ job.status }}"
        curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"✅ Tetris build: $status on branch ${{ github.ref_name }} by ${{ github.actor }}.\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
